<a href="https://colab.research.google.com/github/merazlab/tensorflow/blob/master/Mod_01/mod_01_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [4]:
import tensorflow as tf
print(tensorflow.__version__)

1.15.2


What is Tensor?

    Tensor is a multi-dimensional array with a uniform data type

checks whats data types

    tf.dtypes.DType

In [24]:
a = tf.constant("meraz")
print(type(a))

<class 'tensorflow.python.framework.ops.Tensor'>


In [25]:
print(a)

Tensor("Const_3:0", shape=(), dtype=string)


In [26]:
print(a.get_shape())

()


In [30]:
b = tf.constant([1.0, 2.0, 3.0, 4.0])
print(a.get_shape())

()


In [7]:
with tf.Session() as sess:
    out = sess.run(a)
    print(out)

b'meraz'


#Baics Maths in TF

In [0]:
a = tf.constant(5)
b = tf.constant(5)
c = a+b

In [10]:
print(c)

Tensor("add:0", shape=(), dtype=int32)


In [14]:
with tf.Session() as sess:
    out = sess.run(c)
    print(out)

10


In [0]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
max_val = tf.reduce_max(c)
# Find the index of the largest value
max_val_index = tf.argmax(c)

In [35]:
with tf.Session() as sess: print(sess.run(max_val))

10.0


In [36]:
with tf.Session() as sess: print(sess.run(max_val_index))

[1 0]


#Linear Algebra

In [40]:
random_array = tf.random_normal((2, 3))
with tf.Session() as sess: print(sess.run(random_array))

[[ 0.22922651  0.48307756  2.4761753 ]
 [-0.23928358  0.06830524 -0.06655082]]


In [41]:
identity_ar = tf.ones((3, 4))
with tf.Session() as sess: print(sess.run(identity_ar))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
zeros_ar = tf.ones((3, 4))
with tf.Session() as sess: print(sess.run(zeros_ar))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
fill_mat = tf.fill((3, 3), 5)
identity_ar = tf.ones((3, 4))
with tf.Session() as sess: print(sess.run(fill_mat))

[[5 5 5]
 [5 5 5]
 [5 5 5]]
